name: flutter_im_socket_models
description: A Dart package for WebSocket message models with JSON serialization support.
version: 1.0.0
homepage: https://github.com/MarscoXu/flutter-im-socket-models

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.10.0
  web_socket_channel: ^2.4.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
