name: flutter_im_socket_models
description: Flutter IM WebSocket message models with JSON serialization support
version: 0.1.0
homepage: https://github.com/MarscoXu/flutter-im-socket-models

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0

flutter:
